# DOCUMENT VARIABLES

NAME= chava
CLEAN_FILES+= *.sigla* *symbols* imagens/*~ *.nav *.snm

# PROJECT VARIABLES

GZCAT= zcat
USE_PDFLATEX= true # directly generate .pdf files from the .tex
VIEWPDF= evince

include /usr/share/latex-mk/latex.gmk
